# Generated by Django 5.2.7 on 2025-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama'), ('COMEDY', 'Comedy'), ('SCIFI', 'Sci-Fi'), ('HORROR', 'Horror')], max_length=100),
        ),
    ]
