# Generated by Django 5.2.7 on 2025-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['screening_time']},
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
